select*from customer limit 10;
-- Bussiness Questions
-- what is total rvenue generated by male vs female

select gender, sum(purchase_amount)
from customer 
group by gender;

-- which customer used to discount but still spend more than average purchase amount? 

select customer_id,promo_code_used,purchase_amount
from customer 
where promo_code_used = 'Yes' and 
purchase_amount >= (select avg(purchase_amount) from customer);

-- which are top 5 products with highest average rating reciews?

select item_purchased ,round(avg(review_rating::numeric),2) as "Average_rating"
from customer
group by item_purchased
order by "Average_rating" desc
limit 5;

-- Compare Average purchase amount between standard and express shipping 
select shipping_type, round(avg(purchase_amount),2) as "Average_amount"
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do Subscribed spend more? Compare average spend and total revenue between subscribers 
-- and non-subscribers? 

select subscription_status,
count(customer_id) as "Total_customers",
round(avg(purchase_amount),2) as "aveeage_amount",
sum(purchase_amount) as "revenue"
from customer 
group by subscription_status
order by "revenue";

-- which 5 product have the highest percentage of purchase with discounts applied?
select item_purchased,
round(100*sum(case when promo_code_used = 'Yes' then 1 else 0 end)/count(*),2) as "discount_rate"
from customer 
group by item_purchased
order by "discount_rate" desc
limit 5;

-- Segement customer into new, Returning and Loyal based on their total number
-- of pervious purchases and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'returning'
	else 'Loyal'
	end as "Customer_segment"
from customer
)
select "Customer_segment", count(*) as "Number of Customer"
from customer_type
group by "Customer_segment";

-- what are the top 3 most puchased within each catgory?
with item_count as (
select category,
item_purchased,
count(customer_id) as Total_order,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased
)
select item_rank,Total_order,category,item_purchased 
from item_count
where item_rank <=3;

-- Are Customers who are repeat buyers (more then 5 previous purchased) are also
-- like to subscribe?

select subscription_status,
count(Customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

-- what is revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as revenue
from customer 
group by age_group
order by revenue desc;
